### ISSUE TITLE
Add Sources

### ISSUE THREAD

**Issue by dkniffin** [dkniffin/kinship#4]
Users should be able to create a source with various fields and associated media, and then that source can be listed on one or more fact. Eg: A person's b-date could supported by several facts (some census records, a tombstone, etc)

Some examples of types of sources:
- Census record
- Birth record
- Death record
- Marriage record
- Webpage
- Book
- Newspaper (Obituary)
- Verbal Account
- Written Account (letters)
- Tombstone

**Comment by oddityoverseer13** [comment]
After sources are implemented, a source importer should be added. The idea would be that you give the importer a URL (or perhaps other document types), and it auto populates as many fields as it can, from that source.

**Comment by dkniffin** [comment]
This was added with #34
